// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Cart
    {
        public int CartId { get; set; }
        public int? ProductId { get; set; }
        public int? PurchaseId { get; set; }
        public int? CartAmount { get; set; }

        public virtual Products Product { get; set; }
        public virtual Purchse Purchase { get; set; }
    }
}