// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Delivery
    {
        public Delivery()
        {
            Purchse = new HashSet<Purchse>();
        }

        public int DelId { get; set; }
        public int? PurchseId { get; set; }
        public int? SdelId { get; set; }
        public DateTime? DelDate { get; set; }

        public virtual StatusDelivery Sdel { get; set; }
        public virtual ICollection<Purchse> Purchse { get; set; }
    }
}