// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int? PurchseId { get; set; }
        public int? PaymentDate { get; set; }
        public string PaymentImage { get; set; }

        public virtual Purchse Purchse { get; set; }
    }
}