// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class PizzaRm
    {
        public PizzaRm()
        {
            Products = new HashSet<Products>();
        }

        public int PrId { get; set; }
        public int? CartId { get; set; }
        public int? RmId { get; set; }
        public int? PrAmount { get; set; }
        public string PrName { get; set; }

        public virtual Rm Rm { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}