// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Products
    {
        public Products()
        {
            Cart = new HashSet<Cart>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? ProductPrice { get; set; }
        public string ProductImage { get; set; }
        public int? PrId { get; set; }
        public int? PtypeId { get; set; }

        public virtual PizzaRm Pr { get; set; }
        public virtual Ptype Ptype { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}