// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Ptype
    {
        public Ptype()
        {
            Products = new HashSet<Products>();
        }

        public int PtypeId { get; set; }
        public string PtypeName { get; set; }

        public virtual ICollection<Products> Products { get; set; }
    }
}