// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Purchse
    {
        public Purchse()
        {
            Cart = new HashSet<Cart>();
            Payment = new HashSet<Payment>();
        }

        public int PurchseId { get; set; }
        public int? UserId { get; set; }
        public DateTime? PurchseDate { get; set; }
        public int? PurchseTotol { get; set; }
        public string PurchseSpay { get; set; }
        public int? DelId { get; set; }
        public int? PaymentId { get; set; }

        public virtual Delivery Del { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}