// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Rm
    {
        public Rm()
        {
            PizzaRm = new HashSet<PizzaRm>();
        }

        public int RmId { get; set; }
        public string RmName { get; set; }
        public int? RmPrice { get; set; }
        public string RmImgPath { get; set; }

        public virtual ICollection<PizzaRm> PizzaRm { get; set; }
    }
}