// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class StatusDelivery
    {
        public StatusDelivery()
        {
            Delivery = new HashSet<Delivery>();
        }

        public int SdelId { get; set; }
        public string SdelName { get; set; }

        public virtual ICollection<Delivery> Delivery { get; set; }
    }
}