// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DPizza.Models.Data
{
    public partial class Title
    {
        public Title()
        {
            User = new HashSet<User>();
        }

        public int TitleId { get; set; }
        public string TitleName { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}